---
title: 'Assignment 3: Critique by Design'
author: "Sarah Pearman"
date: "2020-02-02"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("RMariaDB")
library("tidyverse")

```

```{r barplot, echo=FALSE}
year = c(2009,2011)
year = factor(year)
median = c(50,60)

text.data = data.frame(year,median)

 ggplot(data=text.data, aes(x=year, y=median, fill=year)) +
  geom_bar(stat="identity", show.legend=FALSE) +
   labs(title="Teens sending more texts in 2011 than in 2009",
        x="Year",
        y="Median response: Texts sent per day") +
   theme_minimal() +
   scale_fill_manual(values=c("gray","#67a9cf"))
 
demo = c("Boys ages 14-17","Girls ages 14-17")
median = c(50,100)

gender.data = data.frame(demo,median)

 ggplot(data=gender.data, aes(x=demo, y=median, fill=demo)) +
  geom_bar(stat="identity", show.legend=FALSE) +
   labs(title="Older girls remain the most enthusiastic texters",
        x="Older teens, grouped by gender",
        y="Median response: Texts sent per day in 2011") +
   theme_minimal() +
   scale_fill_manual(values=c("#7fbf7b","#af8dc3"))

```